exports.langs = {
  sq: "Albanian",
  ar: "Arabic",
  ca: "Catalan",
  zh: "Chinese (Simplified)",
  hr: "Croatian",
  en: "English",
  et: "Estonian",
  tl: "Filipino",
  fr: "French",
  de: "German",
  hi: "Hindi",
  id: "Indonesian",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  la: "Latin",
  pt: "Portuguese",
  ru: "Russian",
  es: "Spanish",
  sv: "Swedish",
};
